const _api = {
  _api_parameter_add: "api/param/add",
  _api_parameter_edit: "api/param/edit",
  _api_parameter_detail: "api/param/detail/",
  _api_parameter_del: "api/param/del/",
  _api_module_del: "api/mod/del/",
  _api_project_page: "api/pro/page",
  _api_project_detail: "api/pro/detail/",
  _api_project_add: "api/pro/add",
  _api_project_edit: "api/pro/edit",
  _api_project_del: "api/pro/del/",
  _api_module_page: "api/mod/page",
  _api_module_detail: "api/mod/detail/",
  _api_module_add: "api/mod/add",
  _api_module_edit: "api/mod/edit",
  _api_module_del: "api/mod/del/",
  _api_request_page: "api/req/page",
  _api_request_detail: "api/req/detail/",
  _api_request_add: "api/req/add",
  _api_request_edit: "api/req/edit",
  _api_request_del: "api/req/del/",
  _api_field_page: "api/field/page",
  _api_field_detail: "api/field/detail/",
  _api_field_add: "api/field/add",
  _api_field_edit: "api/field/edit",
  _api_field_del: "api/field/del/"
};
export default _api;
